import { Injectable, Logger } from '@nestjs/common';

export interface AiScenarioRecommendation {
    summary: string;
    recommendations: string[];
    rationale?: string;
}

@Injectable()
export class AiScenarioService {
    private readonly logger = new Logger(AiScenarioService.name);

    async recommendForScenario(
        scenario: Record<string, unknown>,
    ): Promise<AiScenarioRecommendation> {
        this.logger.debug('Stub generating scenario recommendations');
        return {
            summary: 'Stub scenario summary',
            recommendations: ['Consider itemized deductions', 'Review tax regime'],
            rationale: 'Generated by stub AI service',
        };
    }
}
